% inceptionresnetv2 - 299
% vgg16 - 224
N = 224;

trainingImages = imageDatastore( ...
    { ...
    'C:\data\Xyllella-Fastidiosa-Dataset\folds\1', ...
    'C:\data\Xyllella-Fastidiosa-Dataset\folds\2' ...
    }, ...
    'IncludeSubfolders',true,...
    'LabelSource','foldernames');

validationImages = imageDatastore( ...
    { ...
    'C:\data\Xyllella-Fastidiosa-Dataset\folds\3', ...
    }, ...
    'IncludeSubfolders',true,...
    'LabelSource','foldernames');

% Set image read function
trainingImages.ReadFcn = @(filename)readAndPreprocessImage(filename, N);
validationImages.ReadFcn = @(filename)readAndPreprocessImage(filename, N);


% Train the network
net = trainDeepLearner( trainingImages, ...
    'epoch', 1, ...
    'network', 'vgg16', ...
    'miniBatchSize', 10, ...
    'freeze', 1, ...
    'gpu', true );

predictedLabels = classify(net,validationImages);

results(foldNo).fold_results = sum(predictedLabels == validationImages.Labels) ...
    / length(predictedLabels);
results(foldNo).prediction = predictedLabels;
results(foldNo).groundTruth = validationImages.Labels;
results(foldNo).time = toc;
