% inceptionresnetv2 - 299
% vgg16 - 224
function test_ai4i_1
N = 299;

%% FOLD 1
trainingImages = imageDatastore( ...
    { ...
    '~/Xyllella-Fastidiosa-Dataset/folds/2', ...
    '~/Xyllella-Fastidiosa-Dataset/folds/3' ...
    }, ...
    'IncludeSubfolders',true,...
    'LabelSource','foldernames');
validationImages = imageDatastore( ...
    { ...
    '~/Xyllella-Fastidiosa-Dataset/folds/1' ...
    }, ...
    'IncludeSubfolders',true,...
    'LabelSource','foldernames');
% Set image read function
trainingImages.ReadFcn = ...
	@(filename)readAndPreprocessImage(filename, N);
validationImages.ReadFcn = ...
	@(filename)readAndPreprocessImage(filename, N);
results1 = inner( trainingImages, validationImages );

%% FOLD 1
trainingImages = imageDatastore( ...
    { ...
    '~/Xyllella-Fastidiosa-Dataset/folds/1', ...
    '~/Xyllella-Fastidiosa-Dataset/folds/3' ...
    }, ...
    'IncludeSubfolders',true,...
    'LabelSource','foldernames');
validationImages = imageDatastore( ...
    { ...
    '~/Xyllella-Fastidiosa-Dataset/folds/2' ...
    }, ...
    'IncludeSubfolders',true,...
    'LabelSource','foldernames');
% Set image read function
trainingImages.ReadFcn = ...
	@(filename)readAndPreprocessImage(filename, N);
validationImages.ReadFcn = ...
	@(filename)readAndPreprocessImage(filename, N);
results2 = inner( trainingImages, validationImages );

%% FOLD 1
trainingImages = imageDatastore( ...
    { ...
    '~/Xyllella-Fastidiosa-Dataset/folds/1', ...
    '~/Xyllella-Fastidiosa-Dataset/folds/2' ...
    }, ...
    'IncludeSubfolders',true,...
    'LabelSource','foldernames');
validationImages = imageDatastore( ...
    { ...
    '~/Xyllella-Fastidiosa-Dataset/folds/3' ...
    }, ...
    'IncludeSubfolders',true,...
    'LabelSource','foldernames');
% Set image read function
trainingImages.ReadFcn = ...
	@(filename)readAndPreprocessImage(filename, N);
validationImages.ReadFcn = ...
	@(filename)readAndPreprocessImage(filename, N);
results3 = inner( trainingImages, validationImages );
save state2019
end

function results = inner( trainingImages, validationImages )
% Train the network
tic
net = trainDeepLearner( trainingImages, ...
    'epoch', 1, ...
    'network', 'inceptionresnetv2', ...
    'miniBatchSize', 10, ...
    'freeze', 0, ...
    'gpu', true );
predictedLabels = classify(net,validationImages);
results.fold_results = sum(predictedLabels == validationImages.Labels) ...
    / length(predictedLabels);
results.prediction = predictedLabels;
results.groundTruth = validationImages.Labels;
results.time = toc;
end
